#!/bin/bash
set -e

REV="$1"
shift
TEST="$1"
shift

if [ -z "$REV" ]; then
    echo "no commit to compare to"
    exit
fi

if [ -z "$TEST" ]; then
    TEST="."
fi

function doBench {
    local TEST="$1"
    shift
    local REV="$1"
    shift
    go test -v -run ^$ -bench "$TEST" -cpu 1 -count 5 "$@" | tee bench-"$REV"
}

if [ ! -e "bench-$REV" ]; then
    if [ "$REV" == "master" ]; then
        # compare current against master
        git stash
        doBench "$TEST" "$REV" "$@"
        git stash pop
    else
        git checkout "$REV" 
        doBench "$TEST" "$REV" "$@"
        git checkout master
    fi
fi

doBench "$TEST" "current" "$@"

benchstat bench-"$REV" bench-current

# rm bench-"$REV" bench-current
